### ISSUE TITLE
Help understanding the project

### ISSUE THREAD

**Issue by juancarlospaco** [myamyu/selenimum#31]
Whats the difference with https://github.com/halonium/halonium or https://github.com/dom96/webdriver ?.

Besides the integration with Docker, but I guess the others can be run in Docker too anyway.
Thanks.
🙂

**Comment by myamyu** [comment]
Thank you for question.

This project can do those same things.
I think that the goal is the same for all of them.

Difference points from https://github.com/dom96/webdriver .
dom96/webdriver has no some method in latest release version. (e.g. findElements, click...) 
(If it had implemented what I wanted methods, I might not have created this project.)

Difference points from  https://github.com/halonium/halonium .
halonium/halonium can do a lot more than this project. (If I had found it first, I might have used it.)
However, I thought it might be a bit complicated and thought it could be written a bit simpler.

I understand halonium/halonium is probably the most complete one.

**Comment by myamyu** [comment]
> Besides the integration with Docker, but I guess the others can be run in Docker too anyway.

Yes, I tried it.

- [use selenimum](https://github.com/myamyu/nim-playground/tree/main/selenium2)
- [use halonium](https://github.com/myamyu/nim-playground/tree/main/selenium3)

Both work the same way.

**Comment by juancarlospaco** [comment]
Thanks!, I understand. 🙂
